server:
  port: 8090
  context-path: /
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/atpos?currentSchema=atpos
    username: atposadmin
    password: atpos1234
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none

#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql: TRACE